mbed_tools/__main__.py, mbed_tools/cli.py, news/20200207.feature, setup.py, tests/test_devices_command_integration.py, tests/test_true.py
=> ✨ Integrate with mbed-devices

.gitattributes, news/20200210.misc
https://git-scm.com/docs/gitattributes#_end_of_line_conversion
=> 🎨 Introduce end-of-line normalization

mbed_tools/__init__.py, mbed_tools/_internal/__init__.py, mbed_tools/_internal/config_cli.py, mbed_tools/_version.py, mbed_tools/cli.py, news/20200402.doc, pyproject.toml, setup.py, tests/_internal/test_config_cli.py, tests/test_devices_command_integration.py
=> 📝 Add license headers

azure-pipelines/build-release.yml, azure-pipelines/steps/generate-spdx-documents.yml, news/20200420.misc
Refactored the CI in order to ensure licensing reports are always uploaded.
=> 💚 CI refactoring with regards to licensing

mbed_tools/cli.py, news/20200416.major
To make it clearer what the current functionality is. This isn't yet a full export of a top-level cmake file.
=> Change export to export-keys temporarily

mbed_tools/cli.py, news/20200430.feature, setup.py
Update mbed-build version and add build command.
=> ✨Add build command

mbed_tools/cli.py, news/20200715101809.misc
=> Remove build and config commands from cli

mbed_tools/cli.py, news/20200717104411.major
Rename export to configure
Depends on another PR
=> cli: Rename export to configure

doc/architecture/decisions/0001-record-architecture-decisions.md, doc/architecture/decisions/0002-move-mbed-config-header-defines-to-cmake.md, news/20200723142705.doc
Add an ADR for removing mbed_config.h
=> ADR for removing mbed config header

MANIFEST.in, news/20200727151049.bugfix
Ensure all data files are uploaded to pypi
=> MANIFEST.in: graft src directory to include all data files

docs/howto/mbed-tools-howto.md, news/20200811162038.doc
Add install instructions for the tool.
- [ x]  This change is covered by existing or additional automated tests.
=> Add install instructions to documentation

.travis.yml, news/20200814183927.feature
Enable Travis-CI to validate latest changes on supported mbed-os
examples.
=> ci: Add travis config file

docs/howto/mbed-tools-howto.md, news/202008251200.doc
* Remove 'Use environment variables` from Install section as it
is related to Project configuration.
* Explain the usage of relative and absolute paths when
using `init` during project creation.
* Update example application usage instructions
* Add new section related to displaying information on project
environment variables.
=> docs: Update `How-to` docs

.travis.yml, news/202009291300.misc, travis-ci/functions.sh
Add the following examples to be built as part of Travis job
- Test kvstore example (K64F)
- Test ble example (NRF52840_DK)
- Test cellular example (WIO_3G)
- Test devicekey example (K66F)
- Test lorawan example (K66F)
- Test crypto example (K64F)
- Test nfc example (DISCO_L475VG_IOT01A)
- Test sockets example (K64F)
- [x ]  This change is covered by existing or additional automated tests.
=> Add new Travis examples

azure-pipelines/build-release.yml, azure-pipelines/steps/tag-and-release.yml, tox.ini
=> [WIP] toxify beta release - DO NOT MERGE

azure-pipelines/build-release.yml, azure-pipelines/steps/tag-and-release.yml, news/202010091200.misc, news/202010091201.misc, tox.ini
Use tox to run the beta and production release
- [x ]  This change is covered by existing or additional automated tests.
=> Use tox to run the beta and production release

CONTRIBUTING.md, DEVELOPMENT.md, README.md, docs/howto/mbed-tools-howto.md, news/202010091700.doc
Advice on using Tox rather than pipenv
- [x ]  This change is covered by existing or additional automated tests.
=> Update documentation to use tox

docs/howto/mbed-tools-howto.md, news/202010261000.doc
fix: formatting issue in `mbed-tools-howto.md`
=> fix: formatting issue in `mbed-tools-howto.md`

CONTRIBUTING.md, README.md, news/20201105153416.doc
Add instructions for creating a production release.
=> Document release process

news/20201111104222.feature, setup.py, src/mbed_tools/cli/main.py, src/mbed_tools/cli/sterm.py, src/mbed_tools/sterm/__init__.py, src/mbed_tools/sterm/terminal.py, tests/cli/test_sterm.py, tests/sterm/test_terminal.py
Implement serial terminal and sterm command.
=> Serial Terminal

news/202011231100.removal, src/mbed_tools/cli/project_management.py
The `deploy` command-line option mentions about REVISION in help context,
which is an unsupported feature at the moment.
Therefore remove this to avoid unnecessary confusion.
=> cli: update `deploy` command help description

news/20201203161101.feature, src/mbed_tools/cli/build.py, src/mbed_tools/cli/configure.py, src/mbed_tools/project/mbed_program.py, tests/cli/test_build.py, tests/cli/test_configure.py, tests/project/test_mbed_program.py
This is a first implementation of #133 
To do:
=> Provide configure with --path-mbed-os (#133)

news/20210217152408.bugfix, src/mbed_tools/build/_internal/config/source.py, src/mbed_tools/lib/python_helpers.py, tests/build/_internal/config/test_source.py, tests/lib/test_python_helpers.py
Consolidate the list to set type conversion code into a function.
Fixes #183
=> Improve handling of config values

news/20210603213250.feature, src/mbed_tools/targets/_internal/data/targets_metadata.json
To add Cortex-A5 support for mbed-tools.
More info: https://github.com/ARMmbed/mbed-os/issues/14715
=> Feature: Add Cortex-A5 Support

news/286.bugfix, news/287.bugfix, src/mbed_tools/cli/configure.py, tests/cli/test_configure.py
=> Improvements to config subcommand
