ARMmbed/mbed-tools

mbed_tools/cli.py
news/20200316.misc
tests/test_devices_command_integration.py

Simplify import path for `mbed-tools` integration. It'll fail until `mbed-devices` is released.
https://github.com/ARMmbed/mbed-devices/pull/52

♻ Simpler integration with mbed-devices

---

mbed_tools/cli.py
news/20200318.feature
setup.py
tests/test_devices_command_integration.py

Subclass `click.Group` so we can catch and log `ToolsErrors`

Catch and log ToolsErrors in main entry point

---

mbed_tools/cli.py
news/20200403.feature
setup.py
tests/test_devices_command_integration.py

Use new context manager for handling tools errors and improved user friendly message about increasing verbosity.
This requires the companion change here (CI will not pass until `mbed-tools-lib` 1.2 is released:
- https://github.com/ARMmbed/mbed-tools-lib/pull/18
Please see https://github.com/ARMmbed/mbed-tools-lib/pull/18 for manual tests.

✨ Improve user facing messages for increasing verbosity

---

mbed_tools/cli.py
news/20200407.feature
setup.py

Adds the export command to mbed-tools.
Usage currently:
`mbed-tools export -o "something" -t "GCC" -m "CY8CPROTO_062_4343W" -p "../mbed-os-example-blinky/"`

Add mbed export

---

mbed_tools/_internal/config_cli.py
news/20200408.bugfix

Just a small spelling error correction.

Fixing spelling error

---

mbed_tools/cli.py
news/20200422.feature
tests/test_devices_command_integration.py

The functionality of `mbed-tools` is determined by a number of Mbed packages, each implementing a different area. To improve the situation that exists with existing tools, where this often leads to confusion with the users, the new version command will print the versions of all Mbed tools packages. This should make it clearer to users that there is more that the single package at play and should make tackling support issues just a little bit easier.
Manual testing
```
▶ mbed-tools --version
mbed-tools: 1.0.0
-----------------
mbed-build: 1.0.0b17
mbed-devices: 1.0.0b70
mbed-project: 0.1.0b16
mbed-targets: 1.0.0b154
mbed-tools-lib: 1.2.0
```

✨ Added --version option to print the version of all Mbed packages

---

azure-pipelines/build-release.yml
news/20200423.feature
setup.py

Python 3.8 is now in common usage:
- Update the package information to indicate Python 3.8 is supported.
- Add jobs to test with Python 3.8 on each host platform.

✨ Declare Python 3.8 support and add to CI

---

mbed_tools/_internal/env_cli.py
mbed_tools/cli.py
news/20200423.misc
tests/_internal/test_config_cli.py

Rename config to env since we want to have the config command free for Mbed config.

🚚 Config to env

---

mbed_tools/cli.py
news/20200428.feature

Adding the 'config' command.  Build will fail until mbed-build is released.

Config command

---

README.md
news/20200428.misc
setup.py

So that we can make future breaking changes to Mbed packages relied on by mbed-tools, a version specifier is set for each Mbed package. This simplifies development, allowing internal interfaces to be changed while ensuring that new tools will not be installed if they are not compatible.

📌Add a version specifier to the dependencies for Mbed packages

---

news/20200701.bugfix
pyproject.toml

The SPDX checker tool couldn't find this licence, so was failing in CI.
Manually declare licence in pyproject.toml

 Declare MIT licence for zipp dependency 

---

mbed_tools/cli.py
news/20200701.feature

Rename this command as it will export a full CMakelists.txt and toolchain file.

 Rename export-keys command to export 

---

DEVELOPMENT.md
news/20200709222031.doc

Add the minimal version requirement on pipenv (>= 2018.11.26).

📝Add the minimal version requirement on pipenv

---

news/20200720152641.bugfix
setup.py

mbed-build was pinned to ~1.1, it's now at 1.2.2.

Update mbed-build dependency

---

news/20200727143830.bugfix
src/mbed_tools/build/_internal/templates/mbed_config.tmpl

Remove gen_config INTERFACE library target.
Set variables instead of using add_definitions calls.
```
(mbed-tools) robwal02@C02X70Z4JHD5 ~/p/m/p/mbed-os-example-blinky (feature-cmake)> mbedtools configure -t GCC_ARM -m k64f
mbed_config.cmake has been generated and written to '/Users/robwal02/projects/mbed/programs/mbed-os-example-blinky/.mbedbuild'
(mbed-tools) robwal02@C02X70Z4JHD5 ~/p/m/p/mbed-os-example-blinky (feature-cmake)> cat .mbedbuild/mbed_config.cmake
set(MBED_TOOLCHAIN "GCC_ARM" CACHE STRING "")
set(MBED_TARGET "K64F" CACHE STRING "")
set(MBED_CPU_CORE "Cortex-M4F" CACHE STRING "")
set(MBED_PROFILE "develop" CACHE STRING "")
list(APPEND MBED_TARGET_LABELS
MCU_K64F
PSA_V7_M
Freescale_EMAC
Freescale
CORTEX
K64F
MCUXpresso_MCUS
FRDM
Target
KPSDK_CODE
LIKE_CORTEX_M4
PSA_Target …
```

Update CMake template

---

codecov.yml
news/20200729200627.misc

We don't want codecov to notify until results for all platforms have been uploaded and the reports merged.

Send codecov notifications after all results uploaded

---

.pre-commit-config.yaml
azure-pipelines/build-release.yml
news/20200730145703.misc
src/mbed_tools/project/mbed_program.py

Remove assert-news check from pre-commit hooks.
Fix assert-news CI for forked repos
Fix failing test

pre-commit-config: Remove assert news check

---

README.md

Fix links to API documentation.
Links followed manually to verify they work.

README: Fix links to API documentation

---

Pipfile
azure-pipelines/steps/install-development-dependencies.yml
news/20200727201841.misc

The CI pipeline was using editable installs, so the tests failed to catch any packaging issues.
We now install the package to `site-packages` in CI, so we're testing what we actually deploy.

Do not install editable version of package in ci

---

news/20200729210710.bugfix
src/mbed_tools/cli/main.py
src/mbed_tools/lib/logging.py
tests/cli/test_devices_command_integration.py

When `ToolsError` exceptions were raised the tools returned an exit code of 0.
Return 1 when `ToolsError` is raised.

Ensure correct exit code is returned when ToolsError is raised

---

news/20200805143228.bugfix
setup.py
src/mbed_tools/build/_internal/cmake_file.py
src/mbed_tools/build/_internal/config/assemble_build_config.py
src/mbed_tools/build/_internal/config/source.py
src/mbed_tools/cli/configure.py
src/mbed_tools/project/mbed_program.py
src/mbed_tools/targets/get_target.py
tests/build/_internal/config/test_assemble_build_config.py
tests/build/_internal/config/test_source.py
tests/build/_internal/test_cmake_file.py
tests/build/_internal/test_find_files.py
tests/cli/test_configure.py
tests/targets/test_get_target.py

The configure command wasn't using the MbedProgram object to find the root directory of the project. Meaning if the user was in a program subdirectory and didn't specify an output path, the config file would be created in the wrong place and the build would fail.
While I'm here, I've tried to remove unnecessary instantiations of the `MbedProgram` and `Target` objects and decouple them from the `build` module. Previously we were creating multiple `MbedProgram` and `Target` objects in different functions. I've pulled the creation of these objects up to the top level command handler. This code could still be improved further but I think this is enough of an improvement for this PR.

Make the configure command use the mbed program root directory as output

---

.pre-commit-config.yaml
news/20200805160557.misc

We don't need to run pytest unless python files change.
mypy doesn't need to be forced to run serially.

pre-commit: Don't run pytest unless python files change

---

news/20200805210417.bugfix
src/mbed_tools/project/_internal/project_data.py
src/mbed_tools/project/mbed_program.py
tests/project/_internal/test_mbed_program.py
tests/project/_internal/test_project_data.py
tests/project/factories.py

If a user manually git clones an Mbed project, and it doesn't contain a
.mbed file, they would have to create it manually. This is not good UX.
Instead check for the presence of an mbed-os.lib file, as this file is
required in all Mbed programs.

project: Remove dependency on .mbed file

---

news/20200810123455.feature
src/mbed_tools/project/_internal/git_utils.py
src/mbed_tools/project/_internal/project_data.py
src/mbed_tools/project/_internal/render_templates.py
src/mbed_tools/project/_internal/templates/CMakeLists.tmpl
src/mbed_tools/project/_internal/templates/__init__.py
src/mbed_tools/project/_internal/templates/gitignore.tmpl
src/mbed_tools/project/_internal/templates/main.tmpl
src/mbed_tools/project/mbed_program.py
tests/project/_internal/test_git_utils.py
tests/project/_internal/test_mbed_program.py
tests/project/_internal/test_project_data.py
tests/project/_internal/test_render_templates.py

Generate a CMakeLists.txt, main.cpp and .gitignore from the "init" command
Depends on: https://github.com/ARMmbed/mbed-tools/pull/45

Generate project startup files from "init" command

---

news/20200813.bugfix
src/mbed_tools/build/_internal/templates/mbed_config.tmpl

Use `CMAKE_BUILD_TYPE ` instead of `MBED_PROFILE`. I've noticed develop is hardcoded. Do tools already provide profile argument? I don't see it in `mbedtools configure --help`. 
My questions: should we just remove `CMAKE_BUILD_TYPE` from the template, and let a user to provide -DCMAKE_BUILD_TYPE to CMake? `mbed compile` provides `--profile` so this would be a user flow change. All profiles are known in the CMake anyway so mbedtools do not know anything about it anymore (compare to the told tools), correct?
Not yet tested, waiting for your feedback how to pass the profile to CMake and I'll test it locally.
cc @hugueskamba

config: fix build type

---

news/20200816123120.bugfix
src/mbed_tools/project/_internal/project_data.py
src/mbed_tools/project/_internal/templates/CMakeLists.tmpl
src/mbed_tools/project/mbed_program.py
tests/project/_internal/test_mbed_program.py

`pathlib.Path.resolve` doesn't make a nonexistent path absolute on Windows.
To fix this call `Path.absolute`, and then resolve any symlinks in the
absolute path to get the canonical potential path to the directory.

init command: Ensure program path is always made absolute

---

ci_scripts/sync_board_database.py
news/20200817142518.misc
tests/ci_scripts/test_sync_board_db.py

The job was failing because it was looking in the wrong place for the board database snapshot.
Also improve news item text formatting and handle "modified" targets.

Fix the "Sync Board Database" nightly CI job

---

news/20200819144454.bugfix
src/mbed_tools/build/_internal/cmake_file.py
src/mbed_tools/build/_internal/templates/mbed_config.tmpl
tests/build/_internal/test_cmake_file.py

The config option `MBED_BUILD_TIMESTAMP` is not used by Mbed OS. But it
is always generated by `mbedtools configure` and for every run
time stamp is different. During build, `MBED_BUILD_TIMESTAMP` is passed
as command line parameter. Due to this, every call to
`mbedtools configure` leads to`ccache` cache miss.

Remove `MBED_BUILD_TIMESTAMP` config option

---

docs/howto/mbed-tools-howto.md
news/202008211200.doc

How to (when using `mbed-tools`):
- Set environment variables to override default
- List USB connected devices to Host machine
- Display help information
- Create a new project for an application
- Create a local copy of an example application
- Configure the project to output cmake scripts
How to (when using `cmake`):
- Set the build parameters
- Build the application which outputs the binaries
Signed-off-by: Vikas Katariya <vikas.katariya@arm.com>

Add further instructions to `How-to`

---

docs/howto/mbed-tools-howto.md
news/202008261300.doc

* Display verbose information with different log levels
* Explain additional details regarding project configuration

docs: Add verbose info to `how-to`

---

Pipfile
news/20200915.feature
src/mbed_tools/build/_internal/cmake_file.py
src/mbed_tools/build/_internal/templates/mbed_config.tmpl
tests/build/_internal/test_cmake_file.py

`MBED_TARGET_SUPPORTED_C_LIBS`, `MBED_PRINTF_LIB` and `MBED_C_LIB` are provided
in the generated configuration CMake module to allow the toolchain to be
configured for the selected printf library and C library.

config: Add CMake printf variable and C library variables to the generated CMake module

---

azure-pipelines/build-release.yml
azure-pipelines/steps/install-development-dependencies.yml
news/20201001170005.feature
tox.ini

`assert-news` will be removed from `mbed-tools-ci-scripts` to reduce maintenance overhead of custom scripts. `towncrier` now supports checking news files.

Use `towncrier.check` instead of `assert-news`

---

.travis.yml
news/20200929104817.feature
setup.cfg
src/mbed_tools/build/__init__.py
src/mbed_tools/build/build.py
src/mbed_tools/build/config.py
src/mbed_tools/cli/build.py
src/mbed_tools/cli/configure.py
src/mbed_tools/cli/main.py
src/mbed_tools/project/_internal/project_data.py
tests/build/test_build.py
tests/build/test_generate_config.py
tests/cli/test_build.py
tests/cli/test_configure.py
tests/project/_internal/test_mbed_program.py
travis-ci/functions.sh

Add build command porcelain

---

news/20200929160957.misc
src/mbed_tools/build/_internal/config/config.py

Do not put macros like MBED_CONF_FILESYSTEM_PRESENT or
MBED_CONF_EVENTS_PRESENT into the applicaiton's generated
mbed_config.cmake file. We will depend on Mbed OS CMake files for each
of these components to define the _PRESENT macro in a
target_compile_definitions() block for the e.g. filesystem or events
CMake targets.
This should be merged immediately before [the Mbed OS companion PR](https://github.com/ARMmbed/mbed-os/pull/13732) is ready. Then, we should merge this PR, do a tools release, merge Mbed OS example PRs, and merge the Mbed OS PR. Without Mbed OS having updated CMake files, these tool changes will break some builds.

configure: Don't emit _PRESENT macros

---

news/20201016135546.misc
tests/build/_internal/config/test_config.py

No test case was added for https://github.com/ARMmbed/mbed-tools/commit/231dbc443bc14b2932f68fda23a6e5fedb94a481 this is causing codecov to fail.

config: Test Config.from_sources ignores 'present' macros

---

news/20201012141322.feature
src/mbed_tools/build/build.py
src/mbed_tools/cli/build.py
tests/cli/test_build.py

So users can easily build for another target, always reconfigure the
project when --mbed-target and --toolchain flags are passed to the build
subcommand.
--clean will now remove the CMake build tree and force a clean rebuild.

Build command improvements

---

docs/howto/mbed-tools-howto.md
news/202010131300.doc
news/202010211355.doc

Build command can be used to configure and build the target
Merge after https://github.com/ARMmbed/mbed-tools/pull/86

docs: Add `build` and `libs` command option

---

.travis.yml
news/202010261100.misc

From Mbed OS 6.4.0 onwards BLE_Button example isn't supported anymore,
therefore update the CI to use BLE_LED example instead

ci: Use BLE_LED example

---

news/66.bugfix
src/mbed_tools/project/_internal/libraries.py
tests/project/_internal/test_project_data.py

It is been observed that `mbedtools clone` command fails if the host
has a redirection in their git config --global.
This is mainly because of url contains `\` which git is unhappy about
Fixes #66

fix: https to ssh redirection on local host machine

---

news/62.bugfix
src/mbed_tools/project/_internal/libraries.py
src/mbed_tools/project/_internal/project_data.py
src/mbed_tools/project/mbed_program.py
src/mbed_tools/project/project.py
tests/project/_internal/test_libraries.py
tests/project/_internal/test_mbed_program.py
tests/project/_internal/test_project_data.py
tests/project/factories.py
tests/project/test_mbed_project.py

Fixes #62 
Removes the check for mbed-os.lib in the MbedProgram::from_url factory.
Changes LibraryReferences::in_ignore_path to use relative path 'parts'.
Removes auto generation of CMakeLists.txt in existing programs.

Fix mbedtools clone for examples containing multiple programs

---

news/20201023.feature
src/mbed_tools/build/_internal/cmake_file.py
src/mbed_tools/build/_internal/templates/mbed_config.tmpl
tests/build/_internal/test_cmake_file.py

Please enter the commit message for your changes. Lines starting
- Added the target config supported_application_profiles support
- Updated the existing test to validate supported_application_profiles target config
- Added the news file

config: Add CMake supported application profiles variable

---

docs/howto/mbed-tools-howto.md
news/202010281400.doc

Update the documentation to reflect the following changes:
* `mbed-tools` will be officially called as Mbed CLI 2. `mbed-tools` is
the python package name
* BLE button example is not supported by Mbed OS 6.4.0 onwards,
therefore recommend using BLE LED instead.
* Reworded few sentences

docs: Mbed CLI 2

---

.travis.yml
news/202011041130.misc
travis-ci/functions.sh

Pypi doesn't always have the lastest CMake releases, so use the official
Kitware apt repo instead.

travis: Get CMake from kitware repo

---

azure-pipelines/steps/publish-code-coverage-results.yml
news/20201106150801.misc

Codecov now apparently supports "tokenless uploads" from azure, which is
our current CI provider. Remove the codecov token from the pipeline
step.

ci: Remove codecov token

---

.travis.yml
news/20201106115920.misc
src/mbed_tools/project/_internal/project_data.py
travis-ci/functions.sh

The feature-cmake branch has been merged to mbed-os and the
mbed-os-examples now. We should not generate CMake files referring to
this branch any longer, nor should our CI try to clone and use those
branches.

Remove references to non-existent git branch

---

.travis.yml
news/20201110140545.bugfix
src/mbed_tools/project/_internal/templates/CMakeLists.tmpl

Mbed OS have changed the names of some variables and cmake functions.
Update the CMakeLists template to reflect these changes.

project: Update CMakeLists.tmpl

---

.travis.yml
news/202011101010.feature
src/mbed_tools/cli/main.py
src/mbed_tools/cli/project_management.py
tests/cli/test_project_management.py

To ensure good usability with the new Mbed tools the command line
options need to harmonize with the old tools.
Therefore change `init` to `new` by keeping the existing
functionality.
Source files for project and CLI command updated to make sure API
calls mean the same externally and internally

Rename `init` to `new` command line option

---

news/202011091500.feature
src/mbed_tools/cli/main.py
src/mbed_tools/cli/project_management.py
src/mbed_tools/project/__init__.py
src/mbed_tools/project/_internal/libraries.py
src/mbed_tools/project/mbed_program.py
src/mbed_tools/project/project.py
tests/cli/test_project_management.py
tests/project/_internal/test_libraries.py
tests/project/_internal/test_mbed_program.py
tests/project/test_mbed_project.py
travis-ci/functions.sh

To ensure good usability with the new Mbed tools the command line
options need to harmonize with the old tools.
Therefore change `checkout` to `deploy` by keeping the existing
functionality.
These are the following changes done:
* Docs updated
* Source files for project and CLI command updated to make sure api
calls mean the same externally and internally
* Unit tests updated with renamed test functions
* Travis job updated

Rename `checkout` to `deploy` command line option

---

news/20201112095757.feature
src/mbed_tools/build/__init__.py
src/mbed_tools/build/exceptions.py
src/mbed_tools/build/flash.py
src/mbed_tools/cli/build.py
tests/build/factories.py
tests/build/test_flash.py
tests/cli/test_build.py

Add `-f/--flash` option to `build` command to flash the generated binary
onto the device connected to host machine.
By default `.bin` file will be used for flashing. If `--hex-file`
option is passed on the command line, then `.hex` will be used.

build: Add flash option to build command

---

news/202011191400.feature
src/mbed_tools/cli/main.py
tests/cli/test_devices_command_integration.py

To ensure good usability with the new Mbed tools the command line
options need to harmonize with the old tools.
Therefore change `devices` to `detect` by keeping the existing
functionality.

Rename `devices` to `detect` command line option

---

.travis.yml
news/202011101200.feature
src/mbed_tools/cli/main.py
src/mbed_tools/cli/project_management.py
src/mbed_tools/project/__init__.py
src/mbed_tools/project/project.py
tests/cli/test_project_management.py
tests/project/test_mbed_project.py

To ensure good usability with the new Mbed tools the command line
options need to harmonize with the old tools.
Therefore change `clone` to `import` by keeping the existing
functionality.
Update the following to reflect the changes done:
* Source files for project and CLI command updated to make sure API
calls mean the same externally and internally
* Unit tests with renamed test functions

Rename `clone` to `import` command line option

---

.travis.yml
news/202011191602.misc

Mbed OS will only depend on released versions of CMake now. Use released
versions of CMake by removing Kitware's release candidate APT
repository.
Fixes #104

travis: Use released CMake versions

---

.travis.yml
news/202011261100.bugfix
src/mbed_tools/cli/project_management.py
src/mbed_tools/project/_internal/git_utils.py
src/mbed_tools/project/_internal/libraries.py
tests/project/_internal/test_git_utils.py
tests/project/_internal/test_libraries.py

Set default branch to master
Make sure we checkout `master` if there is no git hash present in the .lib file.
Perform fetch before checkout
Make sure we fetch git repo before performing checkout when using `deploy` command. This makes sure we have the latest changes in repo.
Tests have been updated to accommodate this issue.
Fixes https://github.com/ARMmbed/mbed-tools/issues/122

Fetch and checkout default branch if no git hash given in .lib file

---

.gitignore
news/20201124142418.feature
src/mbed_tools/build/flash.py
src/mbed_tools/cli/build.py
src/mbed_tools/cli/sterm.py
src/mbed_tools/devices/__init__.py
src/mbed_tools/devices/devices.py
src/mbed_tools/devices/exceptions.py
tests/build/test_flash.py
tests/cli/test_build.py
tests/cli/test_sterm.py
tests/devices/test_mbed_devices.py

Allows users to open a serial terminal to the device after building and flashing their application.

Add --sterm option to the compile command

---

news/202011271738.feature
src/mbed_tools/project/_internal/libraries.py
tests/project/_internal/test_libraries.py

Save time by fetching only the requested ref when a ref is given in a
.lib file.

libraries: Save time by fetching specific refs

---

tests/project/_internal/test_libraries.py

Add back in accidentally deleted assert in
test_does_not_resolve_references_in_ignore_paths().
Fixes: 2a28c185fec3 ("libraries: Save time by fetching specific refs")

Add back in accidentally deleted assert

---

.travis.yml
news/20201127153832.misc
travis-ci/functions.sh

Previously mbed-tools checked for the presence of an mbed-os.lib file
before performing an `import` or `deploy`. We worked around this in
our CI by creating an empty mbed-os.lib at the root of the project
before running the `deploy` command. mbed-tools no longer enforces this
policy, so we can remove the workaround.
After removing the workaround there seems to be no need for the
`_clone_dependencies` function. This commit removes the function. We
can't replace it with `mbedtools import` as that would cause many
unneeded copies of mbed-os to be cloned in the case of the BLE example,
which would slow the CI down significantly. For this reason we keep the
git clone step for the example and run `mbedtools deploy` in the
example/subexample folder to fetch other dependencies.
Fixes #126.

ci: Remove _clone_dependencies from travis CI

---

news/20201130184919.bugfix
src/mbed_tools/build/_internal/config/assemble_build_config.py
src/mbed_tools/build/_internal/config/cumulative_data.py
src/mbed_tools/build/_internal/config/source.py
tests/build/_internal/config/test_assemble_build_config.py
tests/build/_internal/config/test_source.py
tests/regression/test_configure.py

The config options `c_lib` and `printf_lib` have been added to target configuration so that these options can be overridden by application configuration.
Regression test for `mbed-tools configure` command has been added.
Fixes https://github.com/ARMmbed/mbed-tools/issues/109

Add `c_lib` and `printf_lib` to target config options

---

news/20201202121845.misc
pyproject.toml

The "Licence Report" script has started failing as it can't detect the
licence for the `importlib-metadata` package. This package has an
Apache-2.0 licence so is fine for our purposes. Add the licence to the
"Packages With Checked Licences" section of `pyproject.toml` to keep the
CI script happy.

pyproject: Add importlib-metadata license

---

news/20201201142709.bugfix
src/mbed_tools/build/_internal/templates/mbed_config.tmpl
tests/build/_internal/test_cmake_file.py

Always quote option values, being sure to escape literal quotes.
(Parenthesis don't need escaping within strings, so we also remove logic
to catch and handle the presence of parenthesis.) This prevents CMake
from getting confused when quotes are encounted within an option value
and making multiple partial list items from a single list item as
happens with the following mbed_lib.json snippet.
"iotc-mqtt-host": {
"help": "IOTC MQTT host configuration. Defaults to mqtt.2030.ltsapis.goog host and port number 8883 if undefined",
"value": "{\"mqtt.2030.ltsapis.goog\", IOTC_MQTT_PORT}",
"macro_name": "IOTC_MQTT_HOST"
}
Which would produce the following bad CMake output (parsed as three list
items):
"-DIOTC_MQTT_HOST={"mqtt.2030.ltsapis.goog", IOTC_MQTT_PORT}"
Now, after our changed, the output …

config: Always quote option values

---

.pre-commit-config.yaml
news/20201208124121.misc

The license-files script was failing due to an update in the
`licenseheaders` dependency which broke the command line parsing. The
dependency has been pinned to a working version upstream so we need to
update the version for pre-commit.

ci: Update license-files version

---

azure-pipelines/build-and-deploy.yml
azure-pipelines/prep-release.yml
ci_scripts/prep-release
news/20201130143507.misc
tox.ini

Add a pipeline to automate checking in auto generated files and tagging a new release.

ci: Add nightly release pipeline

---

azure-pipelines/analyse-and-test.yml
news/20201209160511.misc
tox.ini

Python 3.9 is now the version `brew` installs by default. Add testing
for Python 3.9 in the CI.
Fixes #146

ci: Add Python3.9 to test matrix

---

README.md
news/20201210131204.bugfix
src/mbed_tools/build/build.py
tests/build/test_build.py

If CMake or Ninja is not found on PATH handle the builtin exception and
emit a more useful error message.
Fixes #149

  build: Add checks for CMake and Ninja installs

---

news/20201208190734.misc
tests/build/test_generate_config.py

Add regression tests at the public interface level so we can rework the
config processing code and have some confidence we haven't broken anything.

Add regression tests for config processing

---

news/20201214165520.feature
src/mbed_tools/build/_internal/config/assemble_build_config.py
src/mbed_tools/build/_internal/config/source.py
src/mbed_tools/build/_internal/find_files.py
src/mbed_tools/lib/json_helpers.py
tests/build/_internal/config/test_source.py
tests/build/test_generate_config.py
tests/lib/test_json_helpers.py

Support for a config option `requires` in `mbed_app.json` is added
which enables application to choose required mbed libraries. if
`requires` is mentioned in `mbed_app.json` then only those mbed
libraries and other libraries those mbed libraries depend on will be
selected. Other mbed libraries are ignored.
Fixes https://github.com/ARMmbed/mbed-tools/issues/127.

config: Add support for `requires` config option

---

azure-pipelines/analyse-and-test.yml
news/20210113.misc
tox.ini

Remove Python 3.7 testing in Tox and CI as it is no longer considered a primary configuration.
Fixes #165

ci: Remove Python3.7 from test matrix

---

.travis.yml
news/20210119095356.misc

The mbed-os-example-lorawan example removed support for building with
targets that don't have radio connections specified in the example's
mbed_app.json. This means we can no longer build the example for the
K66F target. Build for the DISCO_L072CZ_LRWAN1 target instead.

travis: Build lorawan example for DISCO_L072CZ_LRWAN1

---

news/20210121143556.major
src/mbed_tools/cli/build.py

In Mbed CLI 1, `--profile` was used to identify type of build. Change
`--build-type` to `--profile` to match Mbed CLI 1 behaviour.

compile: Update command line option

---

README.md
news/20210127150731.misc

The license report link was dead (404). Remove the badge and link to the
license compliance report.

README: Remove dead link to license report

---

news/20210127171548.feature
src/mbed_tools/targets/_internal/data/targets_metadata.json

Add Cortex-M55 definitions
Nothing to test here, as no new targets in Mbed OS have been added yet. We may need to fix bugs in this addition when trouble pops up with adding the new Mbed OS targets.

targets: Add Cortex-M55 definitions

---

.pre-commit-config.yaml
.travis.yml
ci_scripts/licenseheaders.json
news/20201222090211.feature
src/mbed_tools/build/_internal/cmake_file.py
src/mbed_tools/build/_internal/write_files.py
src/mbed_tools/build/config.py
src/mbed_tools/cli/build.py
src/mbed_tools/project/_internal/git_utils.py
src/mbed_tools/project/_internal/project_data.py
src/mbed_tools/project/_internal/templates/CMakeLists.tmpl
src/mbed_tools/targets/_internal/target_attributes.py
src/mbed_tools/targets/get_target.py
tests/build/_internal/test_cmake_file.py
tests/build/_internal/test_write_files.py
tests/build/test_generate_config.py
tests/cli/test_build.py
tests/project/_internal/test_git_utils.py
tests/targets/_internal/test_target_attributes.py
travis-ci/test-data/TARGET_IMAGINARYBOARD/CMakeLists.txt
travis-ci/test-data/custom_targets.json

Adds support for custom_targets.json in the tools.
This is dependent on [mbed-os CMake changes](https://github.com/ARMmbed/mbed-os/pull/14199). 
Without those changes adding a custom target using `add_subdirectory` will make mbed-os fail to  build for standard mbed targets.
With those changes (once applied to all targets) you can add your target using  `add_subdirectory(<target-dir> EXCLUDE_FROM_ALL)` before adding the mbed-os subdirectory, in the top level CMakeLists.txt, and the custom target will integrate into the build system without breaking it.
While I'm here fix the `deploy --force` option as that was broken.

Add support for custom_targets.json

---

news/141.feature
news/20210203124012.major
src/mbed_tools/cli/build.py
src/mbed_tools/cli/configure.py
src/mbed_tools/project/_internal/project_data.py
src/mbed_tools/project/mbed_program.py
tests/cli/test_build.py
tests/project/_internal/test_project_data.py
tests/project/test_mbed_program.py

Creates new subdirectories in cmake_build for each target/profile/toolchain combination, and writes build tree into these. This will be in `cmake_build/TARGET/PROFILE/TOOLCHAIN`
With these changes multiple target-toolchain combinations can be compiled for without manually moving files or clearing parts of the build tree each time. To ensure clarity with use of multiple targets and toolchains, both will be made to be required arguments for `compile`.
Fixes #141

Add build subdirectories for multiple targets/toolchains

---

news/182.bugfix
src/mbed_tools/build/_internal/config/source.py
tests/build/_internal/config/test_source.py

This PR could support unhashable list of Mbed target.json .
Most list in target.json are string type and could be a set type of python.
However, some targets add integer list, like as:       
```
"sectors": [
[
0,
2048
]
```
This kind type will encounter `TypeError: unhashable type: 'list'` in `source.py` for config preparation.

Support unhashable list of target.json

---

news/20210210161209.major
src/mbed_tools/build/config.py
src/mbed_tools/cli/build.py
src/mbed_tools/cli/configure.py
src/mbed_tools/project/_internal/project_data.py
src/mbed_tools/project/_internal/templates/CMakeLists.tmpl
tests/build/test_generate_config.py
tests/cli/test_build.py
travis-ci/test-data/TARGET_IMAGINARYBOARD/CMakeLists.txt

The `MbedProgramFiles` contains list of files related to an Mbed program. When a new Mbed program gets created then `MbedProgramFiles` is instantiated. However, location of mbed config cmake file `mbed_config.cmake` is not known at this stage. Therefore, move `mbed_config.cmake` to config component where it'll be first used.

config: move mbed config cmake `mbed_config.cmake` file from root to build directory

---

news/191.bugfix
src/mbed_tools/build/_internal/config/config.py
tests/build/_internal/config/test_config.py

Previously, when applying overrides, we were finding the first config
setting with a name that matches the the override name. When different
setting namespaces contained settings with the same name, this led to
applying overrides to only the first setting rather than the correct
setting. To fix this, check both name and namespace when searching for
settings to override.

config: Check namespace when applying overrides

---

.travis.yml
news/20210217153419.misc

Add blinky bare-metal example to travis CI.
Fixes https://github.com/ARMmbed/mbed-tools/issues/98

ci: Add blinky bare-metal example

---

news/169.bugfix
src/mbed_tools/project/mbed_program.py
tests/project/test_mbed_program.py

The parser in the `import` subcommand causes errors when using scp-like `user@host:directory` SSH syntax, as it is not recognized by `urllib.parse` as a standard URL, and is treated as a project name instead. This adds a check for non-standard URLs, using the URL if it meets git scp-like requirements. This does not affect importing ARMmbed projects by name.
Fixes #169

project: Add support for SSH syntax in import

---

news/20210218112043.bugfix
src/mbed_tools/devices/_internal/detect_candidate_devices.py
src/mbed_tools/devices/exceptions.py
tests/devices/_internal/test_detect_candidate_devices.py

Previously the detection code seemed to think if the user wasn't running
Linux or Windows they must be running macOS. That would be great, but
unfortunately this isn't the case and other OSes do exist.
This PR adds an UnknownOSError and raises it when platform.system
detects an OS we don't understand.
Fixes #177

 detect: Raise an error when running on unknown OS

---

.travis.yml
news/20210218122316.bugfix
src/mbed_tools/cli/project_management.py
tests/cli/test_project_management.py

If current directory (".") is passed as argument to `mbed-tools new`
then generated `CMakeList.txt` was missing application target name.
Use absolute path instead of relative path while retrieving path details
from command line.
Fixes https://github.com/ARMmbed/mbed-tools/issues/195

new: Fix for create a new Mbed OS project bug

---

news/181.feature
src/mbed_tools/build/flash.py
src/mbed_tools/cli/build.py
src/mbed_tools/cli/list_connected_devices.py
src/mbed_tools/cli/sterm.py
src/mbed_tools/devices/__init__.py
src/mbed_tools/devices/devices.py
tests/cli/test_build.py
tests/cli/test_list_connected_devices.py
tests/cli/test_sterm.py
tests/devices/test_mbed_devices.py

Refactor device detection to allow for use of multiple of the same device, without having to manually remove, and to clarify default flash behavior in this case.
Previously, if a user had multiple of the same `mbed-target` connected, the behavior of `mbed-tools` was to use the first device found which matches the given `mbed_target`, regardless of how many are connected. That leads to unclear behavior with `compile -f/--sterm`, and `sterm` subcommands, and requires manual disconnecting of devices to flash or start a serial terminal with a specific device.
Modified the default behavior of `compile -f` to find all connected devices of the target type, and flash all that are found, rather than just flashing the first one found.
Allow users to specify a device to use with an ID in `compile` …

devices: Add IDs for devices when multiple of the same type are connected

---

news/20210301122753.bugfix
src/mbed_tools/build/_internal/config/config.py
tests/build/_internal/config/test_config.py
tests/build/test_generate_config.py

To keep backwards compatibility we now just emit a warning message when the user provides an invalid `target_override`.

Emit a warning instead of an error when the user attempts to override an undefined configuration parameter

---

news/20210302104001.bugfix
src/mbed_tools/build/_internal/config/assemble_build_config.py
src/mbed_tools/build/config.py
tests/build/test_generate_config.py

Previously the mbed-os-path wasn't being passed to assemble_config.
This meant if mbed-os was in a directory above the project root no
mbed_lib.json files would be detected as assemble_config was always
searching for mbed_lib.json files from the project root down.
This commit modifies assemble_config to take an iterable of search
paths it will scan for config files.
Fixes #204

config: Pass mbed-os-path to generate_config

---

news/201.bugfix
src/mbed_tools/targets/_internal/board_database.py
src/mbed_tools/targets/get_board.py
tests/targets/test_get_board.py

Previously if a board could not be identified with the offline database, and the online database could not be accessed, the command would fail. Instead, now a clearer error message will be logged and the board will be considered as an unknown board, allowing it to be found with `detect` regardless of network connection.
Example:
```
$ mbed-tools detect -a
ERROR: Unable to access the online database to identify a board.
ERROR: Could not identify a board with the product code: '0799'.
Board name    Serial number             Serial port    Mount point(s)             Build target(s)
------------  ------------------------  -------------  -------------------------  -----------------
<unknown>     0674FF504955857567165732  /dev/ttyACM0   /media/werner/NODE_L4R5ZI
```
Fixes #201

Add support for using unknown boards without access to the online database

---

news/20210303115502.bugfix
src/mbed_tools/targets/_internal/target_attributes.py
tests/targets/_internal/test_target_attributes.py

The targets module has its own mechanism for handling configuration
overrides when parsing targets.json. Improve the error messaging when an
invalid override is encountered and change the error into a warning.

targets: Improve error messaging on invalid target override

---

.travis.yml
news/20210224162840.feature
src/mbed_tools/project/_internal/git_utils.py
src/mbed_tools/project/_internal/libraries.py
tests/project/_internal/test_git_utils.py
tests/project/_internal/test_libraries.py

Without shallow cloning, cloning Mbed OS can take quite a long while.
Clone with a depth of 1 when resolving library dependencies in order to
speed up cloning. A downside of this approach is that the resulting
repository will not contain other git references than the initial one,
but this can be worked around by performing a subsequent fetch using
`git fetch`.
Example performance improvement on one person's internet connection:
- Old speed for Mbed OS cloning: 1 minute 12.19 seconds
- New speed for Mbed OS cloning: 26.57 seconds
Fixes #178
Speed up obtaining library dependencies by obtaining only the requested library
revision and no other revision.

project: Shallow clone repos

---

news/20210304131741.bugfix
src/mbed_tools/targets/_internal/board_database.py
tests/targets/_internal/test_board_database.py

Previously when accessing the board database failed, any `ConnectionError` raised would give the same log message, giving little information about the cause. Additional warning logs are added for two subclasses, `SSLError` and `ProxyError` for more user-friendly information.

targets: Improve logging with requests.get

---

news/200.misc
tests/targets/_internal/test_board_database.py

To make sure we're supporting proxies, test cases are added to check that `http_proxy` and `https_proxy` will be read from when accessing the online board database.
Tests are also added to improve coverage with the board database request code, to make sure that the correct warnings are being logged.

tests: Add cases for board database requests

---

news/171.bugfix
setup.py

This reverts commit b8701297370e4768bc8b7f4e6bab1430eba81689.
Mbed OS has made these dependencies optional. Mbed OS CMake will try to
detect if they are present before using them, displaying a warning if
they are not available. As such, it no longer helps Mbed usability to
have mbed-tools depend on these dependencies it doesn't need. Remove
mbed-os dependencies, which are now optional, from mbed-tools.
Fixes #171

Revert "Add some mbed-os dependencies as our own"

---

news/229.bugfix
src/mbed_tools/devices/devices.py

We used to emit the somewhat enigmatic phrase "There was a problem
detecting your board" when we fail to find a "product code" in the
devices HTM file that matches an entry in the database. Instead of
expecting our users to have a level of deductive reasoning bordering on
the supernatural, actually produce an error message that might help
them in debugging the problem.
Fixes #229

devices: Improve obtuse error message

---

news/20210312114544.misc
tests/targets/_internal/test_board_database.py

When adding tests for proxy support, a test was added which uses `requests` with a non-existent proxy. This is effectively a test of `requests`, rather than a unit test of `mbed-tools`, and is redundant as other tests cover this proxy error using mocks.

tests: Remove redundant board db proxy test

---

news/20210323151402.misc
travis-ci/test-data/custom_targets.json

Form factor ARDUINO has been deprecated and replaced with ARDUINO_UNO.
Update the form factor in our custom_targets.json for the custom target
integration test in travis.

ci: travis: Remove deprecated config option from custom_targets.json

---

news/216.bugfix
src/mbed_tools/build/_internal/templates/mbed_config.tmpl
tests/build/test_generate_config.py

Fixes: #216 
The optional `OUTPUT_EXT` field in Mbed OS `targets.json` specifies the format of the output image. This is important because
* some targets only support one image format
* each post-binary hook outputs one image only
This avoids confusion of having both .hex and .bin images generated while only one of them is usable.
Note: The CMake change in Mbed OS is https://github.com/ARMmbed/mbed-os/pull/14472

config: Add `OUTPUT_EXT`

---

news/20210330104425.feature
src/mbed_tools/devices/_internal/file_parser.py
src/mbed_tools/devices/_internal/resolve_board.py
src/mbed_tools/targets/__init__.py
src/mbed_tools/targets/get_board.py
tests/devices/_internal/test_file_parser.py
tests/devices/_internal/test_resolve_board.py
tests/targets/test_get_board.py

When connecting with J-Link, some files we rely on for identifying the board may not be present. This adds parsers for `Segger.html` and `Board.html` files, and extracts the type of J-Link in use and the slug from the manufacturer's board URL. This slug will not always correspond to the Mbed slug, so an additional function is added to search for the matching board. This attempts to find a board in the database which matches any of `slug`, `board_name` or `board_type` with the extracted slug.

devices: Detect and extract data from J-Link

---

news/245.bugfix
setup.py

We were pinning the version of Click we depend on to 7.1. Pinning to a
specific version of the package is not ideal, as we would have to keep
updating the pinned version to avoid dependency conflicts with newer
Python packages that depend on later versions of Click. We depend on
some Click features that appeared in 7.1, so we do need at least this
version. Later versions of the package should also work for us, so we
don't need to specify the requirement so precisely.
This commit relaxes the requirement to Click 7.1 or greater. This should
minimise the potential for dependency conflicts with other packages.
Fixes #245

setup: Relax Click version requirement

---

news/258.bugfix
src/mbed_tools/devices/_internal/file_parser.py
tests/devices/_internal/test_file_parser.py

We can't guarantee details.txt will be in the form "key: value" with a
":" separator on every line. Sometimes they even end with a trailing
newline. Make the code more lenient by using str.partition instead of
str.split, which will return empty strings if the separator isn't found,
rather than raising an exception.
Fixes #258

devices: Make parser more lenient to unknown layouts

---

news/222.bugfix
src/mbed_tools/build/_internal/config/config.py
src/mbed_tools/build/_internal/config/source.py
src/mbed_tools/build/_internal/templates/mbed_config.tmpl
tests/build/_internal/config/test_config.py
tests/build/_internal/config/test_source.py

MBED_ROM_START/SIZE and MBED_RAM_START/SIZE may be included in config files, to define active memory regions. However, these are currently ignored in the config system, and so are not passed to the compiler.
These attributes are now extracted from the config files, and the definitions are added to `mbed_config.cmake`. Both SIZE and START are required together to define a region, and repeated definition of a memory region is ignored.
Fixes #222

config: Support MBED_ROM_START and friends

---

news/20210512103446.misc
tests/project/_internal/test_project_data.py
tests/project/_internal/test_render_templates.py
tests/project/factories.py
tests/project/test_mbed_program.py

In `test_mbed_program`, `test_project_data` and `test_render_templates`, temporary directories are created either with use of a decorator from `factories.py` or with repetitive code in each test case.
Use of `unittest.TestCase` is removed from these files, and the pytest `tmp_path` fixture is used to provide temporary directories.

Refactor tests to use pytest fixtures and remove TestCase

---

news/20210524113403.bugfix
src/mbed_tools/build/_internal/cmake_file.py
src/mbed_tools/build/_internal/config/config.py
src/mbed_tools/build/_internal/config/source.py
src/mbed_tools/build/_internal/templates/mbed_config.tmpl
tests/build/_internal/config/test_config.py
tests/build/_internal/config/test_source.py
tests/build/test_generate_config.py

MBED_ROM/RAM_START/SIZE overrides were not added to
mbed_config.cmake.
The reason mbed_app.json overrides were "ignored" is
because the overrides were applied to the already collected string
parameters and weren't applied to the extracted `Memory` objects we
expose in the template.
We shouldn't need special handling for mbed_rom/ram_start or
mbed_rom/ram_size as they are already collected (if present in
targets.json). So remove the special handling for memory regions.
A side effect of this approach is that we remove some of the validation
checks for START and SIZE both being defined. If we feel this is a 
necessary check we can add it back into the `Config` object.
Fixes #283

 Fix issue with memory region overrides

---

news/20210524175020.bugfix
src/mbed_tools/build/_internal/config/assemble_build_config.py
src/mbed_tools/build/_internal/find_files.py
tests/build/_internal/config/test_assemble_build_config.py

When `mbed-os-path` was given on the command line, and it happened to be
a subdirectory of the project path it would be searched twice for
mbed_lib.json files. This would cause duplicate config parameter
exceptions to be raised.
Ensure duplicated config file paths are discarded by resolving the
absolute paths. This is so `Path.__eq__` can detect duplicate entries and
they are filtered when building the final set. Also ensure we handle the
case where a subdirectory of the search path is a symlink.
Fixes #234

config: Ensure duplicate config file paths are discarded

---

news/20210602164800.feature
pyproject.toml
src/mbed_tools/build/config.py
src/mbed_tools/cli/build.py
src/mbed_tools/cli/configure.py
tests/build/test_generate_config.py
tests/cli/test_build.py

The default image format is bin, but targets can override it with `"OUTPUT_EXT": "hex"` in `targets.json`. This is already taken care of in the CMake configuration generated by mbed-tools, but user still need to pass `--hex-image` if they want to run `mbed-tools compile` with `--flash` to flash a hex image.
This commit makes the image selection automatic based on `OUTPUT_EXT`.
Note: `--hex-file` is now redundant and thus removed. It does not make sense to have it anymore without also offering `--bin-file` for completeness.
The test cases for bin and hex image flashing have been updated accordingly. Coverage for `OUTPUT_EXT` has been improved, with both `mbed_config.cmake` and image format to flash checked.
The test case for hex image flashing has been updated accordingly.
Also manually …

build: Automatically determine image format to flash

---

news/291.bugfix
src/mbed_tools/cli/build.py
src/mbed_tools/cli/configure.py
tests/cli/test_build.py
tests/cli/test_configure.py

Add an option `--app-config` to `configure` and `compile`, to allow users to specify an application configuration file. If unspecified, mbed-tools will use `mbed_app.json` if the latter exists.
Tests are provided.
Fixes #291
Also: Remove default arguments of `build()` that duplicate what we set with click.

configure/build: Support user-specified application configuration

---

news/262.bugfix
src/mbed_tools/cli/configure.py
tests/cli/test_build.py
tests/cli/test_configure.py

As `mbed-tools compile` supports `-b`, `--profile` for selecting a build profile, the same should exist for `mbed-tools configure` as users may want to manually run the build step using `cmake` in some cases. This PR implements it and supplies a test.
Note: This only affects the build directory - it has no impact on the contents of `mbed_config.cmake`. To actually build an application with a profile, a user needs to either run `mbed-tools compile` with `--profile <profile>`, or manually run `cmake` with `-DCMAKE_BUILD_TYPE=<profile>` after `mbed-tools configure`.
Also add missing test for `--profile` of `mbed-tools compile`.
Fixes #262

configure: Add --profile for profile selection

---

news/20210708144331.misc
src/mbed_tools/build/_internal/templates/mbed_config.tmpl
tests/build/_internal/test_cmake_file.py

The CMake list `MBED_CONFIG_DEFINITIONS` in `mbed_config.cmake` generated by `mbed-tools configure` has each item prepended with `-D`. Mbed OS passes this list to `target_compile_definitions()` which supports macros with or without `-D`.
Dropping `-D` from `MBED_CONFIG_DEFINITIONS` makes the style consistent with `MBED_TARGET_DEFINITIONS` and makes it easier for a library or application to check if a given macro is on the list.

config: Do not prepend definitions with `-D`

---

news/20210720122929.bugfix
src/mbed_tools/project/_internal/templates/CMakeLists.tmpl

CMake expects the top level application to be specified as the top level
project. To do this we need to define the project before adding
dependencies.

project: CMakeLists.tmpl: Fix project definition

---

news/20210720.feature
src/mbed_tools/build/_internal/templates/mbed_config.tmpl
tests/build/test_generate_config.py

Targets that take longer to boot (e.g. TF-M targets which boot MCUboot and TF-M before application) have `forced_reset_timeout` in mbed-os/targets/targets.json to increase timeout after reset before starting a Greentea test. This is previously handled by mbedgt, but as we move to CTest and mbedhtrun, a target's reset timeout needs to be available in CMake and passed to mbedhtrun.

config: Add `MBED_GREENTEA_TEST_RESET_TIMEOUT`

---

news/20210729080119.bugfix
src/mbed_tools/build/_internal/config/assemble_build_config.py
src/mbed_tools/build/_internal/config/config.py
src/mbed_tools/build/_internal/config/source.py
src/mbed_tools/build/config.py
tests/build/_internal/config/test_config.py
tests/build/test_generate_config.py

We were previously replacing the list of "requires" if we happened to
find a set of requires not in the app config. This meant occasionally
some config macros would not be defined for baremetal apps depending on
the order the config files were discovered and parsed.
Now we always append to the list of requires, which is how it's supposed
to work.

Fix requires handling for baremetal config

---

news/233.bugfix
src/mbed_tools/build/config.py
tests/build/test_generate_config.py

Mbed CLI 1 scans and builds all files of supported extensions in a project's directory and subdirectories, unless otherwise ignored. If a user has built a project once with mbed-tools and CMake then tries to build it with Mbed CLI 1, the CMake build directory gets accidentally picked up and results in errors.
To resolve this, let mbed-tools generate a .mbedignore file in the build directory.
Fixes #233.

configure: Generate .mbedignore in build directory

---

azure-pipelines/analyse-and-test.yml
news/202112221149.bugfix
src/mbed_tools/build/_internal/templates/mbed_config.tmpl

Some users may want to include `mbed_config.cmake` in their application
`CMakeLists.txt` and modify some of the preset variables. This is
currently impossible: the variables defined in `mbed_config.cmake` will
be overwritten when the file is included again in the mbed-os root
`CMakeLists.txt`.
We can use CMake's `include_guard` feature to force CMake to skip
processing of the file if it has already been processed previously in the
build.
Azure Pipelines have removed Python 3.6 from the macOS-latest runners.
Python3.6 is nearing end of life so we can remove testing for it.
https://www.python.org/dev/peps/pep-0494/#lifespan

Add include guard to `mbed_config.cmake`

---

.pre-commit-config.yaml
news/2022072013030.misc
setup.py
tests/cli/test_project_management.py

The latest version (8.1.3) of the click package is supported in many
projects. E.g. in CHIP project where mbed-os port is implemented.
https://github.com/project-chip/connectedhomeip
In this case, we need to increase the limit of the click version to 8.1.
We need to also update the black package version to be
compatible with the click.
These changes required fix in TestNewCommand class. We need to use
`Path(<file>).resolve()` which is also use in latest click
implementation.
https://github.com/pallets/click/blob/dc918b48fb9006be683a684b42cc7496ad649b83/src/click/types.py#L853

config: Increase click package required version to 8.1
